# Generated by Django 5.1.7 on 2025-04-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='cover',
            field=models.URLField(default='placeholder_image.jpg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='title',
            field=models.CharField(default='dam', max_length=255),
            preserve_default=False,
        ),
    ]
