# Generated by Django 5.1.7 on 2025-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_favorite_cover_favorite_rating_favorite_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
