# Generated by Django 5.1.7 on 2025-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_favorite_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], default='user', max_length=10),
        ),
    ]
